import 'package:last/utility/hive_models/ingredient_model.dart';

List<NutrientModel> primaryFreshNutrientListTemplate = [
  NutrientModel(nutrientName: "Crude protein", amount: 0.0, unit: 'g/100g'),
  NutrientModel(nutrientName: "Crude fat", amount: 0.0, unit: 'g/100g'),
  NutrientModel(nutrientName: "Crude ash", amount: 0.0, unit: 'g/100g'),
  NutrientModel(nutrientName: "Moisture", amount: 0.0, unit: 'g/100g'),
  NutrientModel(nutrientName: "Crude fiber", amount: 0.0, unit: 'g/100g'),
  NutrientModel(nutrientName: "Calcium", amount: 0.0, unit: 'mg/100g'),
  NutrientModel(nutrientName: "Iron", amount: 0.0, unit: 'mg/100g'),
  NutrientModel(nutrientName: "Magnesium", amount: 0.0, unit: 'mg/100g'),
  NutrientModel(nutrientName: "Phosphorus", amount: 0.0, unit: 'mg/100g'),
  NutrientModel(nutrientName: "Potassium", amount: 0.0, unit: 'mg/100g'),
  NutrientModel(nutrientName: "Sodium", amount: 0.0, unit: 'mg/100g'),
  NutrientModel(nutrientName: "Zinc", amount: 0.0, unit: 'mg/100g'),
  NutrientModel(nutrientName: "Copper", amount: 0.0, unit: 'mg/100g'),
  NutrientModel(nutrientName: "Manganese", amount: 0.0, unit: 'mg/100g'),
  NutrientModel(nutrientName: "Selenium", amount: 0.0, unit: 'µg/100g'),
  NutrientModel(nutrientName: "Vitamin A", amount: 0.0, unit: 'IU/100g'),
  NutrientModel(nutrientName: "Vitamin E", amount: 0.0, unit: 'mg/100g'),
  NutrientModel(nutrientName: "Vitamin D", amount: 0.0, unit: 'IU/100g'),
  NutrientModel(nutrientName: "Vitamin C", amount: 0.0, unit: 'mg/100g'),
  NutrientModel(nutrientName: "Thiamin", amount: 0.0, unit: 'mg/100g'),
  NutrientModel(nutrientName: "Riboflavin", amount: 0.0, unit: 'mg/100g'),
  NutrientModel(nutrientName: "Niacin", amount: 0.0, unit: 'mg/100g'),
  NutrientModel(nutrientName: "Pantothenic", amount: 0.0, unit: 'mg/100g'),
  NutrientModel(nutrientName: "Vitamin B6", amount: 0.0, unit: 'mg/100g'),
  NutrientModel(nutrientName: "Vitamin B12", amount: 0.0, unit: 'µg/100g'),
  NutrientModel(nutrientName: "Choline", amount: 0.0, unit: 'mg/100g'),
  NutrientModel(nutrientName: "Vitamin K1", amount: 0.0, unit: 'µg/100g'),
  NutrientModel(nutrientName: "Folic acid", amount: 0.0, unit: 'µg/100g'),
  NutrientModel(nutrientName: "Tryptophan", amount: 0.0, unit: 'g/100g'),
  NutrientModel(nutrientName: "Threonine", amount: 0.0, unit: 'g/100g'),
  NutrientModel(nutrientName: "Isoleucine", amount: 0.0, unit: 'g/100g'),
  NutrientModel(nutrientName: "Leucine", amount: 0.0, unit: 'g/100g'),
  NutrientModel(nutrientName: "Lysine", amount: 0.0, unit: 'g/100g'),
  NutrientModel(nutrientName: "Methionine", amount: 0.0, unit: 'g/100g'),
  NutrientModel(nutrientName: "Cystine", amount: 0.0, unit: 'g/100g'),
  NutrientModel(nutrientName: "Phenylalanine", amount: 0.0, unit: 'g/100g'),
  NutrientModel(nutrientName: "Tyrosine", amount: 0.0, unit: 'g/100g'),
  NutrientModel(nutrientName: "Valine", amount: 0.0, unit: 'g/100g'),
  NutrientModel(nutrientName: "Arginine", amount: 0.0, unit: 'g/100g'),
  NutrientModel(nutrientName: "Histidine", amount: 0.0, unit: 'g/100g'),
  NutrientModel(nutrientName: "Alanine", amount: 0.0, unit: 'g/100g'),
  NutrientModel(nutrientName: "Aspartic acid", amount: 0.0, unit: 'g/100g'),
  NutrientModel(nutrientName: "Glutamic acid", amount: 0.0, unit: 'g/100g'),
  NutrientModel(nutrientName: "Glycine", amount: 0.0, unit: 'g/100g'),
  NutrientModel(nutrientName: "Proline", amount: 0.0, unit: 'g/100g'),
  NutrientModel(nutrientName: "Serine", amount: 0.0, unit: 'g/100g'),
  NutrientModel(nutrientName: "Linoleic acid", amount: 0.0, unit: 'g/100g'),
  NutrientModel(
      nutrientName: "Alpha linolenic acid", amount: 0.0, unit: 'g/100g'),
  NutrientModel(nutrientName: "Arachidonic acid", amount: 0.0, unit: 'g/100g'),
  NutrientModel(nutrientName: "DHA", amount: 0.0, unit: 'g/100g'),
  NutrientModel(nutrientName: "EPA", amount: 0.0, unit: 'g/100g'),
  NutrientModel(nutrientName: "Chloride", amount: 0.0, unit: 'mg/100g'),
  NutrientModel(nutrientName: "Iodine", amount: 0.0, unit: 'mg/100g'),
  NutrientModel(nutrientName: "Taurine", amount: 0.0, unit: 'g/100g'),
  NutrientModel(nutrientName: "Biotin", amount: 0.0, unit: 'mg/100g'),
  NutrientModel(nutrientName: "L-carnitrine", amount: 0.0, unit: 'g/100g'),
  NutrientModel(nutrientName: "Price", amount: 0.0, unit: 'THB/100g'),
];

List<NutrientModel> secondaryFreshNutrientListTemplate = [
  NutrientModel(
      nutrientName: "Metabolizable energy", amount: 0.0, unit: 'kcal/kg'),
  NutrientModel(nutrientName: "Moisture", amount: 0.0, unit: 'g/100g'),
  NutrientModel(nutrientName: "Crude protein", amount: 0.0, unit: 'g/100g'),
  NutrientModel(nutrientName: "Crude fat", amount: 0.0, unit: 'g/100g'),
  NutrientModel(nutrientName: "Crude ash", amount: 0.0, unit: 'g/100g'),
  NutrientModel(nutrientName: "Crude fiber", amount: 0.0, unit: 'g/100g'),
  NutrientModel(nutrientName: "Starch", amount: 0.0, unit: 'NFE: g/100g'),
  NutrientModel(nutrientName: "Arginine", amount: 0.0, unit: 'g/100g'),
  NutrientModel(nutrientName: "Histidine", amount: 0.0, unit: 'g/100g'),
  NutrientModel(nutrientName: "Isoleucine", amount: 0.0, unit: 'g/100g'),
  NutrientModel(nutrientName: "Leucine", amount: 0.0, unit: 'g/100g'),
  NutrientModel(nutrientName: "Lysine", amount: 0.0, unit: 'g/100g'),
  NutrientModel(nutrientName: "Methionine", amount: 0.0, unit: 'g/100g'),
  NutrientModel(
      nutrientName: "Methionine+Cystine", amount: 0.0, unit: 'g/100g'),
  NutrientModel(nutrientName: "Phenylalanine", amount: 0.0, unit: 'g/100g'),
  NutrientModel(
      nutrientName: "Phenylalanine+Tyrosine", amount: 0.0, unit: 'g/100g'),
  NutrientModel(nutrientName: "Threonine", amount: 0.0, unit: 'g/100g'),
  NutrientModel(nutrientName: "Tryptophan", amount: 0.0, unit: 'g/100g'),
  NutrientModel(nutrientName: "Valine", amount: 0.0, unit: 'g/100g'),
  NutrientModel(nutrientName: "Linoleic acid", amount: 0.0, unit: 'g/100g'),
  NutrientModel(
      nutrientName: "Alpha linolenic acid", amount: 0.0, unit: 'g/100g'),
  NutrientModel(nutrientName: "EPA", amount: 0.0, unit: 'g/100g'),
  NutrientModel(nutrientName: "DHA", amount: 0.0, unit: 'g/100g'),
  NutrientModel(nutrientName: "Arachidonic acid", amount: 0.0, unit: 'g/100g'),
  NutrientModel(nutrientName: "Omega6/Omega3 ratio", amount: 0.0, unit: ''),
  NutrientModel(nutrientName: "Calcium", amount: 0.0, unit: 'mg/100g'),
  NutrientModel(nutrientName: "Phosphorus", amount: 0.0, unit: 'mg/100g'),
  NutrientModel(
      nutrientName: "Calcium/Phosphorus ratio", amount: 0.0, unit: ''),
  NutrientModel(nutrientName: "Potassium", amount: 0.0, unit: 'mg/100g'),
  NutrientModel(nutrientName: "Sodium", amount: 0.0, unit: 'mg/100g'),
  NutrientModel(nutrientName: "Chloride", amount: 0.0, unit: 'mg/100g'),
  NutrientModel(nutrientName: "Magnesium", amount: 0.0, unit: 'mg/100g'),
  NutrientModel(nutrientName: "Iron", amount: 0.0, unit: 'mg/100g'),
  NutrientModel(nutrientName: "Copper", amount: 0.0, unit: 'mg/100g'),
  NutrientModel(nutrientName: "Manganese", amount: 0.0, unit: 'mg/100g'),
  NutrientModel(nutrientName: "Zinc", amount: 0.0, unit: 'mg/100g'),
  NutrientModel(nutrientName: "Iodine", amount: 0.0, unit: 'mg/100g'),
  NutrientModel(nutrientName: "Selenium", amount: 0.0, unit: 'µg/100g'),
  NutrientModel(nutrientName: "Vitamin A", amount: 0.0, unit: 'IU/100g'),
  NutrientModel(nutrientName: "Vitamin D", amount: 0.0, unit: 'IU/100g'),
  NutrientModel(nutrientName: "Vitamin E", amount: 0.0, unit: 'mg/100g'),
  NutrientModel(nutrientName: "Thiamin", amount: 0.0, unit: 'mg/100g'),
  NutrientModel(nutrientName: "Riboflavin", amount: 0.0, unit: 'mg/100g'),
  NutrientModel(nutrientName: "Pantothenic", amount: 0.0, unit: 'mg/100g'),
  NutrientModel(nutrientName: "Niacin", amount: 0.0, unit: 'mg/100g'),
  NutrientModel(nutrientName: "Vitamin B6", amount: 0.0, unit: 'mg/100g'),
  NutrientModel(nutrientName: "Folic acid", amount: 0.0, unit: 'µg/100g'),
  NutrientModel(nutrientName: "Vitamin B12", amount: 0.0, unit: 'µg/100g'),
  NutrientModel(nutrientName: "Choline", amount: 0.0, unit: 'mg/100g'),
  NutrientModel(nutrientName: "Glutamic acid", amount: 0.0, unit: 'g/100g'),
  NutrientModel(nutrientName: "Taurine", amount: 0.0, unit: 'g/100g'),
  NutrientModel(nutrientName: "Vitamin K1", amount: 0.0, unit: 'µg/100g'),
  NutrientModel(nutrientName: "Vitamin C", amount: 0.0, unit: 'mg/kg'),
  NutrientModel(nutrientName: "Total Omega 3", amount: 0.0, unit: 'g/100g'),
  NutrientModel(nutrientName: "Biotin", amount: 0.0, unit: 'mg/100g'),
  NutrientModel(nutrientName: "L-carnitrine", amount: 0.0, unit: 'g/100g'),
  NutrientModel(nutrientName: "Price", amount: 0.0, unit: 'THB/100g'),
  //
  // NutrientModel(nutrientName: "Cystine", amount: 0.0, unit: 'g/100g'),
  // NutrientModel(nutrientName: "Tyrosine", amount: 0.0, unit: 'g/100g'),
  // NutrientModel(nutrientName: "Alanine", amount: 0.0, unit: 'g/100g'),
  // NutrientModel(nutrientName: "Aspartic acid", amount: 0.0, unit: 'g/100g'),
  // NutrientModel(nutrientName: "Glycine", amount: 0.0, unit: 'g/100g'),
  // NutrientModel(nutrientName: "Proline", amount: 0.0, unit: 'g/100g'),
  // NutrientModel(nutrientName: "Serine", amount: 0.0, unit: 'g/100g'),
];
